name: matrix-registration
channels:
  - conda-forge
dependencies:
  - alembic=1.13.1
  - appdirs=1.4.4
  - attrs=23.2.0
  - blinker=1.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - deprecated=1.2.14
  - flask=3.0.2
  - flask-cors=4.0.0
  - flask-httpauth=4.8.0
  - flask-limiter=3.5.1
  - flask-sqlalchemy=3.0.3
  - greenlet=3.0.3
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib-resources=6.1.2
  - importlib_resources=6.1.2
  - itsdangerous=2.1.2
  - jinja2=3.1.3
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - krb5=1.21.2
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libexpat=2.5.0
  - libffi=3.4.2
  - libpq=16.2
  - libsqlite=3.45.1
  - libzlib=1.2.13
  - limits=3.9.0
  - mako=1.3.2
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - ncurses=6.4
  - openssl=3.2.1
  - ordered-set=4.1.0
  - packaging=23.2
  - parameterized=0.9.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - psycopg2=2.9.9
  - psycopg2-binary=2.9.9
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.12.2
  - python_abi=3.12
  - pyyaml=6.0.1
  - readline=8.2
  - referencing=0.33.0
  - requests=2.31.0
  - rich=13.7.1
  - rpds-py=0.18.0
  - setuptools=69.1.1
  - six=1.16.0
  - sqlalchemy=2.0.28
  - tk=8.6.13
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - waitress=3.0.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - wrapt=1.16.0
  - wtforms=3.1.2
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
